services:
  - type: web
    name: realtime-chat
    env: node
    plan: free
    buildCommand: npm install && npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
